Update blank.yml
Tokaage/IT-Genius pull request #6
Opened 2022-02-25 20:29 UTC by Tokaage

2022-02-25 20:34 UTC, dmitrii-kruglov requested changes
Не хватает блок схемы, к сожалению, это было одно из условий домашней работы. Жду обновлений

2022-02-25 20:34 UTC, dmitrii-kruglov commented on .github/workflows/blank.yml
> +#include <iostream>
Это лишнее наверно?

2022-02-25 20:34 UTC, dmitrii-kruglov commented on .github/workflows/blank.yml
> +void print_corr(char c, int x)
BP: добавить описание функции в комментарии

2022-02-25 20:34 UTC, dmitrii-kruglov commented on .github/workflows/blank.yml
> +    if ((c >= 'a') && (c <= 'h') && (x >= 1) && (x <= 8))
Интересное решение)

2022-03-17 10:33 UTC, closed without merging

2022-03-17 12:24 UTC, dmitrii-kruglov commented
Мне не понятно, стоит ли смотреть. Но блок схема не от этого решения

2022-03-17 12:24 UTC, dmitrii-kruglov commented
И комментарии не исправлены

2022-03-21 21:53 UTC, Tokaage commented
> Мне не понятно, стоит ли смотреть. Но блок схема не от этого решения

Смотреть не стоит, я думал, что это уже закрытый pull request.